import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time environment variables — generated by envied.
///
/// Values come from `.env` at build time. Never committed to source.
/// Run `flutter pub run build_runner build` after creating/changing `.env`.
@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'SUPABASE_PROJECT_ID')
  static const String supabaseProjectId = _Env.supabaseProjectId;

  @EnviedField(varName: 'SUPABASE_ANON_PUBLIC', obfuscate: true)
  static final String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Optional override — set `SUPABASE_URL` in `.env` to point at a non-hosted
  /// instance (e.g. `http://127.0.0.1:54321` for local `supabase start`).
  /// Leave empty in prod so the URL is derived from [supabaseProjectId].
  @EnviedField(varName: 'SUPABASE_URL', defaultValue: '')
  static const String _supabaseUrlOverride = _Env._supabaseUrlOverride;

  /// Supabase API URL — the override wins when present, otherwise derived
  /// from the project ID (production default).
  static String get supabaseUrl =>
      _supabaseUrlOverride.isNotEmpty
          ? _supabaseUrlOverride
          : 'https://$supabaseProjectId.supabase.co';

  @EnviedField(varName: 'UNLEASH_URL', obfuscate: true)
  static final String unleashUrl = _Env.unleashUrl;

  @EnviedField(varName: 'UNLEASH_CLIENT_KEY', obfuscate: true)
  static final String unleashClientKey = _Env.unleashClientKey;

  @EnviedField(varName: 'SENTRY_DSN', obfuscate: true)
  static final String sentryDsn = _Env.sentryDsn;
}
