import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time environment variables — generated by envied.
///
/// Values come from `.env` at build time. Never committed to source.
/// Run `flutter pub run build_runner build` after creating/changing `.env`.
@Envied(path: '.env')
abstract class Env {
  /// Supabase project ID. Used in prod to derive the API URL when
  /// [SUPABASE_URL] override is not set. Empty locally — the URL
  /// override covers every dev use case.
  @EnviedField(varName: 'SUPABASE_PROJECT_ID', defaultValue: '')
  static const String supabaseProjectId = _Env.supabaseProjectId;

  @EnviedField(varName: 'SUPABASE_ANON_PUBLIC', obfuscate: true)
  static final String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Optional override — set `SUPABASE_URL` in `.env` to point at a non-hosted
  /// instance (e.g. `http://127.0.0.1:54321` for local `supabase start`).
  /// Leave empty in prod so the URL is derived from [supabaseProjectId].
  @EnviedField(varName: 'SUPABASE_URL', defaultValue: '')
  static const String _supabaseUrlOverride = _Env._supabaseUrlOverride;

  /// Supabase API URL — the override wins when present, otherwise derived
  /// from the project ID (production default).
  static String get supabaseUrl =>
      _supabaseUrlOverride.isNotEmpty
          ? _supabaseUrlOverride
          : 'https://$supabaseProjectId.supabase.co';

  /// Unleash Frontend API URL. Empty locally — skip remote calls in
  /// [initUnleash] and return `false` for every flag. In prod this is
  /// the self-hosted Unleash instance URL.
  @EnviedField(varName: 'UNLEASH_URL', obfuscate: true, defaultValue: '')
  static final String unleashUrl = _Env.unleashUrl;

  /// Unleash Frontend API client key. Empty locally.
  @EnviedField(varName: 'UNLEASH_CLIENT_KEY', obfuscate: true, defaultValue: '')
  static final String unleashClientKey = _Env.unleashClientKey;

  /// Sentry DSN. Empty locally — `initSentry` skips init and errors print
  /// to the debug console only.
  @EnviedField(varName: 'SENTRY_DSN', obfuscate: true, defaultValue: '')
  static final String sentryDsn = _Env.sentryDsn;
}
