/// Pre-push coverage gate — ensures new/changed Dart files have ≥80% test coverage.
///
/// Mirrors SonarCloud's "Coverage on New Code" quality gate locally so coverage
/// issues are caught before PR creation, not after CI runs.
///
/// Usage: `dart run scripts/check_new_code_coverage.dart`
///
/// How it works:
/// 1. Runs `flutter test --coverage` to generate coverage/lcov.info
/// 2. Identifies new/changed lib/*.dart files via `git diff` against base branch
/// 3. Checks each file's line coverage in lcov.info
/// 4. Fails if any new file has <80% coverage (matching SonarCloud threshold)
///
/// Skips: generated files (.g.dart, .freezed.dart), barrel exports, constants-only files.
library;

import 'dart:io';

const int _minCoveragePercent = 80;

/// Files to skip (generated code, constants, interfaces, barrel exports).
bool _shouldSkip(String path) {
  if (path.endsWith('.g.dart')) return true;
  if (path.endsWith('.freezed.dart')) return true;
  if (!path.startsWith('lib/')) return true;
  // Barrel exports (only contain `export` statements)
  if (RegExp(r'/(?:badges|cards)\.dart$').hasMatch(path)) return true;
  // Token/constant-only files (no logic to test)
  if (path.contains('_tokens.dart')) return true;
  // Abstract interfaces (domain repositories) — no executable code
  if (path.contains('domain/repositories/')) return true;
  // Design system constants (colors, spacing, radius, typography)
  if (path.contains('core/design_system/') && !path.contains('theme.dart')) {
    return true;
  }
  // Route constants
  if (path.endsWith('routes.dart')) return true;
  return false;
}

/// Parse lcov.info into a map of file path → (hit, total) line counts.
Map<String, (int hit, int total)> _parseLcov(String lcovContent) {
  final result = <String, (int, int)>{};
  String? currentFile;
  int hit = 0;
  int total = 0;

  for (final line in lcovContent.split('\n')) {
    if (line.startsWith('SF:')) {
      currentFile = line.substring(3).replaceAll('\\', '/');
    } else if (line.startsWith('LH:')) {
      hit = int.tryParse(line.substring(3)) ?? 0;
    } else if (line.startsWith('LF:')) {
      total = int.tryParse(line.substring(3)) ?? 0;
    } else if (line == 'end_of_record' && currentFile != null) {
      result[currentFile] = (hit, total);
      currentFile = null;
      hit = 0;
      total = 0;
    }
  }
  return result;
}

/// Detect the best base ref for diffing.
///
/// Priority:
/// 1. COVERAGE_BASE_BRANCH env var (explicit override)
/// 2. The upstream tracking branch of the current branch
/// 3. Fallback to origin/dev
Future<String> _detectBaseRef() async {
  // 1. Explicit override
  final envBase = Platform.environment['COVERAGE_BASE_BRANCH'];
  if (envBase != null && envBase.isNotEmpty) {
    final ref = envBase.startsWith('origin/') ? envBase : 'origin/$envBase';
    stdout.writeln('Using base from COVERAGE_BASE_BRANCH: $ref');
    return ref;
  }

  // 2. Try the upstream tracking branch
  final trackResult = await Process.run('git', [
    'rev-parse',
    '--abbrev-ref',
    '--symbolic-full-name',
    '@{upstream}',
  ]);

  if (trackResult.exitCode == 0) {
    final upstream = (trackResult.stdout as String).trim();
    if (upstream.isNotEmpty && upstream != '@{upstream}') {
      stdout.writeln('Using upstream tracking branch: $upstream');
      return upstream;
    }
  }

  // 3. Fallback
  stdout.writeln('Using default base: origin/dev');
  return 'origin/dev';
}

Future<void> main() async {
  stdout.writeln('Checking new-code coverage (≥$_minCoveragePercent%)...');

  final baseRef = await _detectBaseRef();

  // 1. Get changed lib/*.dart files vs base
  final diffResult = await Process.run('git', [
    'diff',
    '--name-only',
    '--diff-filter=ACMR', // Added, Copied, Modified, Renamed
    '$baseRef...HEAD',
  ]);

  if (diffResult.exitCode != 0) {
    stderr.writeln('Failed to get git diff against $baseRef: ${diffResult.stderr}');
    exit(1);
  }

  final changedFiles =
      (diffResult.stdout as String)
          .split('\n')
          .map((f) => f.trim())
          .where((f) => f.endsWith('.dart') && f.startsWith('lib/'))
          .where((f) => !_shouldSkip(f))
          .toList();

  if (changedFiles.isEmpty) {
    stdout.writeln(
      'No new/changed lib/*.dart files — skipping coverage check.',
    );
    exit(0);
  }

  stdout.writeln('Found ${changedFiles.length} changed file(s) to check.');

  // 2. Check if coverage/lcov.info exists (generated by flutter test --coverage)
  final lcovFile = File('coverage/lcov.info');
  if (!lcovFile.existsSync()) {
    stderr.writeln(
      'coverage/lcov.info not found. Running flutter test --coverage...',
    );
    final testResult = await Process.run('flutter', [
      'test',
      '--coverage',
      '--no-pub',
    ]);
    if (testResult.exitCode != 0) {
      stderr.writeln('Tests failed:\n${testResult.stderr}');
      exit(1);
    }
  }

  // 3. Parse coverage data
  final lcovContent = lcovFile.readAsStringSync();
  final coverage = _parseLcov(lcovContent);

  // 4. Check each changed file
  final failures = <String>[];
  var checkedCount = 0;

  for (final file in changedFiles) {
    // Normalize path for matching (lcov may use backslashes on Windows)
    final normalizedFile = file.replaceAll('\\', '/');
    final entry = coverage.entries.where((e) {
      final lcovPath = e.key.replaceAll('\\', '/');
      return lcovPath.endsWith(normalizedFile) || lcovPath == normalizedFile;
    });

    if (entry.isEmpty) {
      // File not in coverage report — likely no tests at all
      failures.add('  0.0%  $file (NO COVERAGE DATA — missing tests?)');
      checkedCount++;
      continue;
    }

    final (hit, total) = entry.first.value;
    if (total == 0) continue; // Skip files with no executable lines

    final pct = (hit / total * 100).round();
    checkedCount++;

    if (pct < _minCoveragePercent) {
      failures.add('  $pct%  $file ($hit/$total lines)');
    }
  }

  // 5. Report
  if (failures.isEmpty) {
    stdout.writeln(
      'All $checkedCount changed file(s) meet $_minCoveragePercent% coverage.',
    );
    exit(0);
  }

  stderr.writeln(
    '\nCoverage gate FAILED — ${failures.length} file(s) below $_minCoveragePercent%:\n',
  );
  for (final f in failures) {
    stderr.writeln(f);
  }
  stderr.writeln(
    '\nFix: Write tests for the files above, then re-run.\n'
    'This check mirrors the SonarCloud "Coverage on New Code" quality gate.',
  );
  exit(1);
}
